# Generated by Django 4.0.6 on 2022-07-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
