# Generated by Django 4.0.6 on 2022-07-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_rename_tokens_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Transcription',
        ),
    ]
